import { ChecklistCategory } from "@/lib/interfaces";

export const BUDGETING_CHECKLIST: ChecklistCategory[] = [
  {
    id: "income",
    title: "Income Sources",
    items: [
      { id: "salary", label: "Salary" },
      { id: "bonus", label: "Bonus" },
      { id: "sidehustle", label: "Side Hustle" },
      { id: "rentalincome", label: "Rental Income" },
      { id: "investmentincome", label: "Investment Income" },
      { id: "otherincome", label: "Other Income" },
      {
        id: "interestincome",
        label: "Interest Income",
      },
      { id: "dividendincome", label: "Dividend Income" },
      { id: "pension", label: "Pension" },
      { id: "socialsecurity", label: "Social Security" },
      { id: "alimony", label: "Alimony" },
      { id: "childsupport", label: "Child Support" },
      { id: "unemployment", label: "Unemployment Benefits" },
      { id: "royalties", label: "Royalties" },
    ],
  },
  {
    id: "expenses",
    title: "Expenses",
    items: [
      { id: "housing", label: "Housing" },
      { id: "utilities", label: "Utilities" },
      { id: "groceries", label: "Groceries" },
      { id: "transportation", label: "Transportation" },
      { id: "insurance", label: "Insurance" },
      { id: "entertainment", label: "Entertainment" },
      { id: "savings", label: "Savings" },
      { id: "healthcare", label: "Healthcare" },
      { id: "clothing", label: "Clothing" },
      { id: "childcare", label: "Childcare" },
      { id: "debtrepayment", label: "Debt Repayment" },
      { id: "subscriptions", label: "Subscriptions" },
      { id: "travel", label: "Travel" },
      { id: "giftsdonations", label: "Gifts and Donations" },
      { id: "otherexpenses", label: "Other Expenses" },
    ],
  },
  {
    id: "debt",
    title: "Debt Payments",
    items: [
      { id: "creditcard", label: "Credit Card Payments" },
      { id: "studentloan", label: "Student Loan Payments" },
      { id: "mortgage", label: "Mortgage Payments" },
      { id: "carloan", label: "Car Loan Payments" },
      { id: "personalloan", label: "Personal Loan Payments" },
      { id: "homeequityloan", label: "Home Equity Loan Payments" },
      { id: "businessloan", label: "Business Loan Payments" },
      { id: "medicaldebt", label: "Medical Debt Payments" },
      { id: "taxdebt", label: "Tax Debt Payments" },
      { id: "otherdebt", label: "Other Debt Payments" },
    ],
  },
  {
    id: "savings",
    title: "Savings Goals",
    items: [
      { id: "emergencyfund", label: "Emergency Fund" },
      { id: "vacation", label: "Vacation Fund" },
      { id: "retirement", label: "Retirement Fund" },
      { id: "education", label: "Education Fund" },
      { id: "homepurchase", label: "Home Purchase Fund" },
      { id: "carpurchase", label: "Car Purchase Fund" },
      { id: "wedding", label: "Wedding Fund" },
      { id: "homeimprovement", label: "Home Improvement Fund" },
      { id: "charity", label: "Charity Fund" },
      { id: "othergoals", label: "Other Savings Goals" },
    ],
  },
  {
    id: "investment",
    title: "Investment Accounts",
    items: [
      { id: "401k", label: "401(k)" },
      { id: "ira", label: "IRA" },
      { id: "brokerage", label: "Brokerage Account" },
      { id: "rothira", label: "Roth IRA" },
      { id: "hsa", label: "Health Savings Account (HSA)" },
      { id: "529plan", label: "529 College Savings Plan" },
      { id: "pension", label: "Pension Plan" },
      { id: "realestate", label: "Real Estate Investments" },
      { id: "cryptocurrency", label: "Cryptocurrency Investments" },
      { id: "otherinvestments", label: "Other Investments" },
    ],
  },
];
