import { ChecklistCategory } from "@/lib/interfaces";

export const DEBT_MANAGEMENT_CHECKLIST: ChecklistCategory[] = [
  {
    id: "debtManagement",
    title: "Debt Management Documents",
    items: [
      { id: "creditReport", label: "Credit Report" },
      { id: "debtStatements", label: "Debt Statements" },
      { id: "loanAgreements", label: "Loan Agreements" },
      { id: "paymentHistory", label: "Payment History" },
      { id: "debtSettlementLetters", label: "Debt Settlement Letters" },
      { id: "bankruptcyDocuments", label: "Bankruptcy Documents" },
      { id: "debtCounselingRecords", label: "Debt Counseling Records" },
      { id: "financialAffidavit", label: "Financial Affidavit" },
      { id: "incomeVerification", label: "Income Verification" },
      { id: "assetDocumentation", label: "Asset Documentation" },
      { id: "debtManagementPlan", label: "Debt Management Plan" },
      {
        id: "creditCounselingCertificate",
        label: "Credit Counseling Certificate",
      },
      { id: "debtReductionStrategy", label: "Debt Reduction Strategy" },
      { id: "negotiationLetters", label: "Negotiation Letters" },
      { id: "settlementAgreements", label: "Settlement Agreements" },
      { id: "paymentArrangements", label: "Payment Arrangements" },
      { id: "communicationRecords", label: "Communication Records" },
    ],
  },
  {
    id: "debtManagementPlan",
    title: "Debt Management Plan Documents",
    items: [
      { id: "budget", label: "Budget" },
      { id: "debtManagementPlan", label: "Debt Management Plan" },
      { id: "paymentSchedule", label: "Payment Schedule" },
      {
        id: "creditCounselingCertificate",
        label: "Credit Counseling Certificate",
      },
      { id: "debtReductionStrategy", label: "Debt Reduction Strategy" },
      { id: "financialGoals", label: "Financial Goals" },
      { id: "monthlyExpenses", label: "Monthly Expenses" },
      { id: "incomeSources", label: "Income Sources" },
      { id: "debtRepaymentPlan", label: "Debt Repayment Plan" },
      { id: "savingsPlan", label: "Savings Plan" },
      { id: "emergencyFundPlan", label: "Emergency Fund Plan" },
    ],
  },
  {
    id: "debtNegotiation",
    title: "Debt Negotiation Documents",
    items: [
      { id: "negotiationLetters", label: "Negotiation Letters" },
      { id: "settlementAgreements", label: "Settlement Agreements" },
      { id: "paymentArrangements", label: "Payment Arrangements" },
      { id: "communicationRecords", label: "Communication Records" },
      { id: "debtValidationLetters", label: "Debt Validation Letters" },
      { id: "creditorCorrespondence", label: "Creditor Correspondence" },
      { id: "paymentHistory", label: "Payment History" },
      { id: "financialAffidavit", label: "Financial Affidavit" },
      { id: "incomeVerification", label: "Income Verification" },
      { id: "assetDocumentation", label: "Asset Documentation" },
    ],
  },
  {
    id: "debtConsolidation",
    title: "Debt Consolidation Documents",
    items: [
      {
        id: "consolidationLoanAgreement",
        label: "Consolidation Loan Agreement",
      },
      { id: "newPaymentTerms", label: "New Payment Terms" },
      { id: "creditReportUpdate", label: "Credit Report Update" },
      { id: "debtConsolidationPlan", label: "Debt Consolidation Plan" },
      { id: "paymentHistory", label: "Payment History" },
      { id: "debtCounselingRecords", label: "Debt Counseling Records" },
      { id: "financialAffidavit", label: "Financial Affidavit" },
      { id: "incomeVerification", label: "Income Verification" },
      { id: "assetDocumentation", label: "Asset Documentation" },
    ],
  },
  {
    id: "debtRelief",
    title: "Debt Relief Documents",
    items: [
      { id: "debtReliefProgram", label: "Debt Relief Program" },
      { id: "eligibilityDocuments", label: "Eligibility Documents" },
      { id: "debtReliefAgreement", label: "Debt Relief Agreement" },
      { id: "paymentHistory", label: "Payment History" },
      { id: "debtCounselingRecords", label: "Debt Counseling Records" },
      { id: "financialAffidavit", label: "Financial Affidavit" },
      { id: "incomeVerification", label: "Income Verification" },
      { id: "assetDocumentation", label: "Asset Documentation" },
    ],
  },
  {
    id: "debtManagementResources",
    title: "Debt Management Resources",
    items: [
      {
        id: "financialLiteracyMaterials",
        label: "Financial Literacy Materials",
      },
      { id: "debtManagementWebinars", label: "Debt Management Webinars" },
      { id: "creditCounselingResources", label: "Credit Counseling Resources" },
      { id: "debtManagementApps", label: "Debt Management Apps" },
      { id: "financialPlanningTools", label: "Financial Planning Tools" },
      { id: "budgetingTools", label: "Budgeting Tools" },
      { id: "debtReductionCalculators", label: "Debt Reduction Calculators" },
      { id: "financialEducationCourses", label: "Financial Education Courses" },
      { id: "debtManagementBlogs", label: "Debt Management Blogs" },
      { id: "financialPodcasts", label: "Financial Podcasts" },
    ],
  },
  {
    id: "debtManagementSupport",
    title: "Debt Management Support",
    items: [
      { id: "supportGroups", label: "Support Groups" },
      { id: "financialAdvisors", label: "Financial Advisors" },
      { id: "debtCounselors", label: "Debt Counselors" },
      { id: "legalAidResources", label: "Legal Aid Resources" },
      { id: "creditCounselors", label: "Credit Counselors" },
      { id: "financialCoaches", label: "Financial Coaches" },
      { id: "communityResources", label: "Community Resources" },
      { id: "onlineForums", label: "Online Forums" },
      { id: "debtManagementHotlines", label: "Debt Management Hotlines" },
      {
        id: "financialEducationWorkshops",
        label: "Financial Education Workshops",
      },
    ],
  },
  {
    id: "debtManagementMonitoring",
    title: "Debt Management Monitoring",
    items: [
      { id: "creditScoreMonitoring", label: "Credit Score Monitoring" },
      { id: "debtTrackingTools", label: "Debt Tracking Tools" },
      { id: "financialHealthCheckups", label: "Financial Health Checkups" },
      { id: "debtManagementProgressReports", label: "Progress Reports" },
      { id: "budgetReview", label: "Budget Review" },
      { id: "debtReductionProgress", label: "Debt Reduction Progress" },
      { id: "financialGoalTracking", label: "Financial Goal Tracking" },
      { id: "monthlyStatements", label: "Monthly Statements" },
      { id: "annualCreditReport", label: "Annual Credit Report" },
      { id: "debtManagementPlanReview", label: "Debt Management Plan Review" },
    ],
  },
  {
    id: "debtManagementGoals",
    title: "Debt Management Goals",
    items: [
      { id: "debtReductionGoals", label: "Debt Reduction Goals" },
      { id: "financialStabilityGoals", label: "Financial Stability Goals" },
      {
        id: "creditScoreImprovementGoals",
        label: "Credit Score Improvement Goals",
      },
      { id: "savingsGoals", label: "Savings Goals" },
      { id: "financialEducationGoals", label: "Financial Education Goals" },
      { id: "budgetingGoals", label: "Budgeting Goals" },
      { id: "emergencyFundGoals", label: "Emergency Fund Goals" },
      { id: "retirementPlanningGoals", label: "Retirement Planning Goals" },
      { id: "investmentGoals", label: "Investment Goals" },
      {
        id: "financialIndependenceGoals",
        label: "Financial Independence Goals",
      },
    ],
  },
  {
    id: "debtManagementSuccess",
    title: "Debt Management Success",
    items: [
      { id: "debtFreeStatus", label: "Debt-Free Status" },
      { id: "financialIndependence", label: "Financial Independence" },
      { id: "improvedCreditScore", label: "Improved Credit Score" },
      { id: "financialWellness", label: "Financial Wellness" },
      { id: "savingsAchievements", label: "Savings Achievements" },
      { id: "financialGoalsAchieved", label: "Financial Goals Achieved" },
      { id: "debtReductionSuccess", label: "Debt Reduction Success" },
      {
        id: "financialEducationAcquired",
        label: "Financial Education Acquired",
      },
      { id: "budgetingSuccess", label: "Budgeting Success" },
      { id: "emergencyFundEstablished", label: "Emergency Fund Established" },
    ],
  },
];
