import { ChecklistCategory } from "@/lib/interfaces";

export const INVESTMENT_CHECKLIST: ChecklistCategory[] = [
  {
    id: "investment",
    title: "Investment Documents",
    items: [
      { id: "brokerage", label: "Brokerage account statements" },
      { id: "401k", label: "401(k) statements" },
      { id: "ira", label: "IRA account statements" },
      { id: "dividend", label: "Dividend income statements" },
      { id: "interest", label: "Interest income statements" },
      { id: "capitalgains", label: "Capital gains and losses" },
      { id: "stocktrades", label: "Stock trade confirmations" },
      { id: "mutualfunds", label: "Mutual fund statements" },
      { id: "realestate", label: "Real estate investment documents" },
      { id: "cryptocurrency", label: "Cryptocurrency transaction records" },
    ],
  },
  {
    id: "taxes",
    title: "Tax Documents",
    items: [
      { id: "taxreturn", label: "Previous year's tax return" },
      { id: "w2", label: "W-2 forms from employers" },
      { id: "1099", label: "1099 forms (contractor, freelance)" },
      { id: "investmentincome", label: "Investment income statements" },
      { id: "rentalincome", label: "Rental property income documentation" },
      { id: "foreignincome", label: "Foreign income statements" },
      { id: "alimonyreceived", label: "Alimony received documentation" },
      { id: "trustincome", label: "Trust income statements" },
      { id: "partnershipincome", label: "Partnership income statements" },
      { id: "dividends", label: "Dividend income statements" },
      { id: "interestincome", label: "Interest income statements" },
    ],
  },
  {
    id: "financial",
    title: "Financial Documents",
    items: [
      { id: "bankstatements", label: "Bank statements" },
      { id: "loanagreements", label: "Loan agreements" },
      { id: "creditcardstatements", label: "Credit card statements" },
      { id: "insurancepolicies", label: "Insurance policies" },
      { id: "estateplanning", label: "Estate planning documents" },
      { id: "financialstatements", label: "Financial statements" },
      { id: "investmentstrategy", label: "Investment strategy documents" },
      { id: "taxplanning", label: "Tax planning documents" },
      { id: "retirementplanning", label: "Retirement planning documents" },
      { id: "financialplanning", label: "Financial planning documents" },
    ],
  },
  {
    id: "other",
    title: "Other Documents",
    items: [
      { id: "trustdocuments", label: "Trust documents" },
      { id: "partnershipagreements", label: "Partnership agreements" },
      { id: "businessdocuments", label: "Business ownership documents" },
      { id: "foreignincome", label: "Foreign income statements" },
      { id: "alimonyreceived", label: "Alimony received documentation" },
    ],
  },
  {
    id: "investmentstrategy",
    title: "Investment Strategy Documents",
    items: [
      { id: "investmentpolicy", label: "Investment policy statement" },
      { id: "riskassessment", label: "Risk assessment documents" },
      { id: "portfolioallocation", label: "Portfolio allocation strategy" },
      { id: "investmentresearch", label: "Investment research reports" },
      { id: "financialgoals", label: "Financial goals and objectives" },
      { id: "investmenthorizon", label: "Investment horizon documents" },
      { id: "assetallocation", label: "Asset allocation strategy" },
      { id: "investmentperformance", label: "Investment performance reports" },
      { id: "investmentreview", label: "Investment review documents" },
      { id: "investmentmonitoring", label: "Investment monitoring reports" },
    ],
  },
  {
    id: "taxplanning",
    title: "Tax Planning Documents",
    items: [
      { id: "taxstrategy", label: "Tax strategy documents" },
      { id: "taxlossharvesting", label: "Tax loss harvesting records" },
      {
        id: "charitablecontributions",
        label: "Charitable contribution records",
      },
      { id: "retirementplanning", label: "Retirement planning documents" },
      { id: "estateplanning", label: "Estate planning documents" },
    ],
  },
  {
    id: "financialplanning",
    title: "Financial Planning Documents",
    items: [
      { id: "budget", label: "Personal budget" },
      { id: "networthstatement", label: "Net worth statement" },
      { id: "cashflowstatement", label: "Cash flow statement" },
      { id: "debtmanagement", label: "Debt management plan" },
      { id: "emergencyfund", label: "Emergency fund documentation" },
      { id: "financialgoals", label: "Financial goals and objectives" },
      { id: "insurancecoverage", label: "Insurance coverage analysis" },
      { id: "retirementplanning", label: "Retirement planning documents" },
      { id: "estateplanning", label: "Estate planning documents" },
      { id: "investmentstrategy", label: "Investment strategy documents" },
    ],
  },
  {
    id: "retirementplanning",
    title: "Retirement Planning Documents",
    items: [
      { id: "retirementaccounts", label: "Retirement account statements" },
      { id: "pensionplans", label: "Pension plan documents" },
      { id: "socialsecurity", label: "Social Security statements" },
      { id: "retirementincome", label: "Retirement income projections" },
      { id: "withdrawalstrategy", label: "Withdrawal strategy documents" },
    ],
  },
];
