import { ChecklistCategory } from "@/lib/interfaces";

export const RETIREMENT_CHECKLIST: ChecklistCategory[] = [
  {
    id: "retirement",
    title: "Retirement Accounts",
    items: [
      { id: "401k", label: "401(k) statements" },
      { id: "ira", label: "IRA account statements" },
      { id: "pension", label: "Pension plan documents" },
      { id: "socialsecurity", label: "Social Security statements" },
      { id: "rmd", label: "Required Minimum Distribution (RMD) notices" },
      { id: "hsa", label: "Health Savings Account (HSA) statements" },
      { id: "rothira", label: "Roth IRA account statements" },
      { id: "sepira", label: "SEP IRA account statements" },
      { id: "simpleira", label: "SIMPLE IRA account statements" },
      { id: "403b", label: "403(b) account statements" },
      { id: "457b", label: "457(b) account statements" },
      { id: "thrift", label: "Thrift Savings Plan (TSP) statements" },
      { id: "annuities", label: "Annuity contracts and statements" },
      { id: "foreignpension", label: "Foreign pension plan documents" },
      { id: "retirementbenefits", label: "Retirement benefits statements" },
      { id: "retirementincome", label: "Retirement income projections" },
      { id: "withdrawalstrategy", label: "Withdrawal strategy documents" },
      { id: "retirementplanning", label: "Retirement planning documents" },
    ],
  },
  {
    id: "investment",
    title: "Investment Accounts",
    items: [
      { id: "brokerage", label: "Brokerage account statements" },
      { id: "mutualfunds", label: "Mutual fund statements" },
      { id: "realestate", label: "Real estate investment documents" },
      { id: "cryptocurrency", label: "Cryptocurrency transaction records" },
      { id: "stocktrades", label: "Stock trade confirmations" },
      { id: "dividend", label: "Dividend income statements" },
      { id: "interest", label: "Interest income statements" },
      { id: "capitalgains", label: "Capital gains and losses" },
      { id: "investmentstrategy", label: "Investment strategy documents" },
      { id: "investmentpolicy", label: "Investment policy statement" },
      { id: "riskassessment", label: "Risk assessment documents" },
      { id: "portfolioallocation", label: "Portfolio allocation strategy" },
      { id: "investmentresearch", label: "Investment research reports" },
    ],
  },
  {
    id: "taxes",
    title: "Tax Documents",
    items: [
      { id: "taxreturn", label: "Previous year's tax return" },
      { id: "w2", label: "W-2 forms from employers" },
      { id: "1099", label: "1099 forms (contractor, freelance)" },
      { id: "investmentincome", label: "Investment income statements" },
      { id: "rentalincome", label: "Rental property income documentation" },
      { id: "foreignincome", label: "Foreign income statements" },
      { id: "alimonyreceived", label: "Alimony received documentation" },
      { id: "trustincome", label: "Trust income statements" },
      { id: "partnershipincome", label: "Partnership income statements" },
      { id: "dividends", label: "Dividend income statements" },
      { id: "interest", label: "Interest income statements" },
      { id: "capitalgains", label: "Capital gains and losses" },
    ],
  },
  {
    id: "estateplanning",
    title: "Estate Planning Documents",
    items: [
      { id: "will", label: "Will" },
      { id: "trust", label: "Trust documents" },
      { id: "powerofattorney", label: "Power of attorney documents" },
      { id: "healthcareproxy", label: "Healthcare proxy documents" },
      { id: "livingwill", label: "Living will" },
      { id: "beneficiarydesignations", label: "Beneficiary designations" },
      { id: "estateinventory", label: "Estate inventory documents" },
      { id: "estatevaluation", label: "Estate valuation documents" },
      { id: "estateplanningstrategy", label: "Estate planning strategy" },
      { id: "taxplanning", label: "Tax planning documents" },
      { id: "charitableplanning", label: "Charitable planning documents" },
      { id: "trustfunds", label: "Trust funds documentation" },
      { id: "estateadministration", label: "Estate administration documents" },
    ],
  },
  {
    id: "financial",
    title: "Financial Documents",
    items: [
      { id: "bankstatements", label: "Bank statements" },
      { id: "loanagreements", label: "Loan agreements" },
      { id: "creditcardstatements", label: "Credit card statements" },
      { id: "insurancepolicies", label: "Insurance policies" },
      { id: "estateplanning", label: "Estate planning documents" },
      { id: "financialgoals", label: "Financial goals and objectives" },
      { id: "budgeting", label: "Budgeting documents" },
      { id: "cashflowstatements", label: "Cash flow statements" },
      { id: "networthstatements", label: "Net worth statements" },
      { id: "investmentaccounts", label: "Investment account statements" },
    ],
  },
  {
    id: "other",
    title: "Other Documents",
    items: [
      { id: "foreignincome", label: "Foreign income statements" },
      { id: "alimonyreceived", label: "Alimony received documentation" },
      { id: "trustdocuments", label: "Trust documents" },
      { id: "partnershipagreements", label: "Partnership agreements" },
      { id: "businessdocuments", label: "Business ownership documents" },
      { id: "taxplanning", label: "Tax planning documents" },
      { id: "investmentstrategy", label: "Investment strategy documents" },
      { id: "financialplanning", label: "Financial planning documents" },
      { id: "retirementplanning", label: "Retirement planning documents" },
    ],
  },
];
