import { ChecklistCategory } from "@/lib/interfaces";

export const TAX_CHECKLIST: ChecklistCategory[] = [
  {
    id: "income",
    title: "Income Documents",
    items: [
      { id: "w2", label: "W-2 forms from employers" },
      { id: "1099", label: "1099 forms (contractor, freelance)" },
      {
        id: "investment",
        label: "Investment income statements (1099-DIV, 1099-INT)",
      },
      { id: "rental", label: "Rental property income documentation" },
      { id: "socialsecurity", label: "Social Security benefits statements" },
      { id: "unemployment", label: "Unemployment benefits statements" },
      { id: "otherincome", label: "Other income documentation" },
      { id: "selfemployment", label: "Self-employment income records" },
      { id: "retirement", label: "Retirement account distributions (1099-R)" },
      { id: "gambling", label: "Gambling winnings and losses" },
      { id: "foreign", label: "Foreign income statements" },
      { id: "alimony", label: "Alimony received documentation" },
      { id: "royalties", label: "Royalties and licensing income" },
      { id: "trust", label: "Trust income statements" },
      { id: "partnership", label: "Partnership income statements" },
      { id: "dividends", label: "Dividend income statements" },
      { id: "interest", label: "Interest income statements" },
      { id: "capitalgains", label: "Capital gains and losses" },
    ],
  },
  {
    id: "deductions",
    title: "Deductions",
    items: [
      { id: "mortgage", label: "Mortgage interest statements (Form 1098)" },
      { id: "charitable", label: "Charitable donation receipts" },
      { id: "medical", label: "Medical expenses documentation" },
      { id: "education", label: "Education expenses (Form 1098-T)" },
      { id: "business", label: "Business expenses records" },
      { id: "retirementcontributions", label: "Retirement contributions" },
      { id: "stateandlocaltaxes", label: "State and local taxes paid" },
      { id: "investmentexpenses", label: "Investment expenses documentation" },
      { id: "homeoffice", label: "Home office expenses" },
      { id: "casualtylosses", label: "Casualty and theft losses" },
      { id: "studentloaninterest", label: "Student loan interest statements" },
      { id: "alimonypaid", label: "Alimony paid documentation" },
      { id: "movingexpenses", label: "Moving expenses documentation" },
      { id: "jobsearch", label: "Job search expenses" },
      { id: "taxprep", label: "Tax preparation fees" },
      { id: "investmentinterest", label: "Investment interest expenses" },
      { id: "gamblinglosses", label: "Gambling losses documentation" },
      { id: "foreigntaxes", label: "Foreign taxes paid" },
      { id: "childcareexpenses", label: "Childcare expenses" },
      { id: "adoption", label: "Adoption expenses" },
      { id: "healthsavings", label: "Health savings account contributions" },
      { id: "ira", label: "IRA contributions" },
      { id: "selfemployedhealth", label: "Self-employed health insurance" },
      { id: "educator", label: "Educator expenses" },
      { id: "stateandlocaltaxespaid", label: "State and local taxes paid" },
      { id: "casualtylosses", label: "Casualty and theft losses" },
      { id: "taxespaid", label: "Taxes paid documentation" },
      { id: "investmentinterest", label: "Investment interest expenses" },
    ],
  },
  {
    id: "credits",
    title: "Tax Credits",
    items: [
      { id: "childcare", label: "Childcare expenses" },
      { id: "energy", label: "Energy-efficient home improvement receipts" },
      { id: "educationcredit", label: "Education credits documentation" },
      { id: "retirement", label: "Retirement savings contributions" },
      { id: "adoption", label: "Adoption expenses documentation" },
      { id: "foreign", label: "Foreign tax credit documentation" },
      { id: "healthcare", label: "Healthcare coverage documentation" },
      { id: "earnedincome", label: "Earned income tax credit documentation" },
      { id: "saver", label: "Saver's credit documentation" },
      { id: "residentialenergy", label: "Residential energy credits" },
      { id: "childtaxcredit", label: "Child tax credit documentation" },
      { id: "othercredits", label: "Other tax credits documentation" },
      { id: "firsttimehomebuyer", label: "First-time homebuyer credit" },
      { id: "healthcoverage", label: "Health coverage tax credit" },
      { id: "adoption", label: "Adoption tax credit" },
      { id: "disabledaccess", label: "Disabled access credit" },
    ],
  },
];
