export const jobPostings = [
  {
    title: "Senior Financial Analyst",
    salary: "$110,000 – $135,000",
    location: "Remote (USA preferred)",
    about:
      "You’ll design the core logic behind our financial calculators and simulators. This role is pivotal in shaping the integrity and reliability of our financial products. You’ll work closely with engineering and product management to validate model assumptions, integrate updates reflecting evolving financial and tax policies, and ensure our tools remain compliant, educational, and high-impact. As a financial expert on the team, you'll translate complex finance principles into usable and transparent algorithms for the public. You’ll also be responsible for documenting the logic and assumptions behind our models, ensuring they are clear and understandable for both internal teams and external users. You’ll be a key player in our mission to empower users with accurate and accessible financial tools.",
    responsibilities: [
      "Build and refine financial models used in our tools (IRA, tax, debt, real estate).",
      "Collaborate with product and UX teams to ensure calculators are both technically sound and user-friendly.",
      "Research financial regulations and apply changes to tools proactively.",
      "Act as an internal subject matter expert for personal finance, investment, and tax-related concepts.",
      "Ensure compliance with federal/state financial standards and best practices.",
      "Review and document logic for transparency and audits.",
      "Train junior team members and assist in peer reviews of financial logic.",
    ],
    requirements: [
      "5+ years in personal finance, tax, or investment analysis.",
      "Proven modeling experience in Excel, Python, or equivalent.",
      "Strong writing and documentation skills.",
      "Ability to translate financial concepts into plain language.",
      "Experience collaborating with engineering and product teams.",
    ],
  },
  {
    title: "Full-Stack Software Engineer (TypeScript/Next.js)",
    salary: "$125,000 – $155,000",
    location: "Remote",
    about:
      "You’ll develop and maintain the frontend and backend systems that power our financial tools and simulator platform. This includes creating secure, fast, and accessible applications using a modern stack. You’ll be responsible for integrating business logic, ensuring reliability, and enabling seamless user interactions. You’ll collaborate closely with designers, analysts, and QA to launch new features and products. You’ll also be involved in architectural decisions, code reviews, and mentoring junior developers. Your work will directly impact the user experience and the performance of our tools, making them more efficient and user-friendly. You’ll be a key player in our mission to provide high-quality financial tools that are accessible to everyone.",
    responsibilities: [
      "Build user-facing tools with Next.js, Tailwind CSS, and ShadCN.",
      "Design APIs and data flows for calculator logic and simulator state management.",
      "Implement accessibility standards and responsive layouts.",
      "Contribute to code reviews, automated testing, and CI/CD processes.",
      "Optimize performance of frontend and backend code for fast user experiences.",
      "Participate in architectural decisions and long-term tech planning.",
      "Document technical processes and provide mentorship when needed.",
    ],
    requirements: [
      "4+ years in full-stack development.",
      "Proficiency with TypeScript, React, and serverless functions.",
      "Experience building data-driven tools or dashboards.",
      "Understanding of REST/GraphQL and headless architecture.",
      "Passion for building accessible and scalable web applications.",
    ],
  },
  {
    title: "UX/UI Designer (Finance Focus)",
    salary: "$95,000 – $120,000",
    location: "Remote",
    about:
      "You’ll design interfaces that make financial decision-making easy and engaging. Your role is central to ensuring users find our tools not only usable but delightful. You’ll create flows, wireframes, and prototypes that turn complex data into accessible visual experiences. You will work with engineers, product managers, and financial experts to design calculators, simulators, and comparison tools with a sharp focus on clarity, inclusivity, and accessibility.",
    responsibilities: [
      "Design responsive, intuitive interfaces for financial tools and dashboards.",
      "Collaborate with developers to ensure feasibility and fidelity of designs.",
      "Conduct user research and usability testing to iterate on product designs.",
      "Establish and maintain design systems and accessibility guidelines.",
      "Create wireframes, mockups, and interactive prototypes using Figma.",
      "Translate complex financial logic into visual patterns that support comprehension.",
      "Contribute to branding and visual identity as needed.",
    ],
    requirements: [
      "3+ years of UX/UI design experience in product-focused teams.",
      "Proficiency in Figma or similar design tools.",
      "Strong understanding of accessibility (WCAG) and inclusive design principles.",
      "Experience designing responsive web applications.",
      "Familiarity with financial or data-intensive applications preferred.",
    ],
  },
  {
    title: "Content Strategist & Technical Writer",
    salary: "$80,000 – $105,000",
    location: "Remote",
    about:
      "You’ll craft and maintain high-quality, accessible content for our financial tools, blog, and educational materials. This role is essential in communicating complex concepts in ways that empower users to make confident financial decisions. You’ll partner with analysts, designers, and developers to document tools, explain calculations, and create a consistent voice across all user-facing assets.",
    responsibilities: [
      "Write and edit clear, concise content for tools, simulators, and comparison pages.",
      "Document calculation logic and provide transparency for methodologies.",
      "Develop educational content (e.g., blog posts, guides, FAQs).",
      "Work with SEO and product teams to align content with strategy.",
      "Create style guides and voice standards for all written materials.",
      "Proof content for accuracy, grammar, and accessibility standards.",
      "Manage content updates in response to legal or financial changes.",
    ],
    requirements: [
      "3+ years in content strategy, copywriting, or technical writing.",
      "Strong understanding of personal finance and financial terminology.",
      "Experience working with design and product teams in an agile environment.",
      "Excellent writing, editing, and organizational skills.",
      "Familiarity with markdown, CMS platforms, or documentation tools.",
    ],
  },
  {
    title: "Product Manager (Financial Tools)",
    salary: "$115,000 – $140,000",
    location: "Remote (US or Canada)",
    about:
      "You’ll drive the vision, strategy, and execution of our financial tools platform. You’ll gather insights from users, stakeholders, and data to prioritize features and ensure we build tools that solve real financial challenges. You’ll collaborate with cross-functional teams to bring simulators, calculators, and comparison tools to life, with a strong focus on impact and user value.",
    responsibilities: [
      "Define product roadmaps and prioritize feature development.",
      "Work closely with design, engineering, and financial analysts to deliver updates and new tools.",
      "Conduct competitive analysis and identify gaps in our offerings.",
      "Own KPIs and track tool usage, user satisfaction, and retention metrics.",
      "Engage with users to validate pain points and test hypotheses.",
      "Document product requirements and user stories clearly.",
      "Advocate for user needs and accessibility in all product decisions.",
    ],
    requirements: [
      "4+ years in product management, preferably in fintech or SaaS.",
      "Strong understanding of personal finance tools and user needs.",
      "Experience with agile methodologies and cross-functional team collaboration.",
      "Ability to make data-driven decisions and manage trade-offs.",
      "Excellent communication and stakeholder management skills.",
    ],
  },
  {
    title: "Marketing Manager (Fintech Focus)",
    salary: "$90,000 – $115,000",
    location: "Remote",
    about:
      "You’ll lead our marketing efforts to promote our financial tools and simulators. This includes developing campaigns, managing social media, and creating content that resonates with our target audience. You’ll work closely with product, design, and content teams to ensure our messaging is clear, impactful, and aligned with our brand values.",
    responsibilities: [
      "Develop and execute marketing strategies for product launches.",
      "Manage social media channels and engage with our community.",
      "Create compelling content for blogs, newsletters, and promotional materials.",
      "Analyze marketing performance metrics and adjust strategies accordingly.",
      "Collaborate with product and design teams to ensure brand consistency.",
      "Conduct market research to identify trends and user needs.",
      "Build partnerships with influencers and organizations in the finance space.",
    ],
    requirements: [
      "3+ years in marketing, preferably in fintech or tech industries.",
      "Strong understanding of digital marketing channels and analytics tools.",
      "Experience creating content that educates and engages users.",
      "Excellent communication skills and attention to detail.",
      "Ability to work collaboratively in a remote team environment.",
    ],
  },
  {
    title: "Customer Support Specialist (Finance Tools)",
    salary: "$50,000 – $65,000",
    location: "Remote",
    about:
      "You’ll be the first point of contact for users seeking help with our financial tools. Your role is crucial in ensuring users have a positive experience and can effectively use our simulators and calculators. You’ll respond to inquiries, troubleshoot issues, and provide educational resources to empower users in their financial decision-making.",
    responsibilities: [
      "Respond to user inquiries via email, chat, and social media.",
      "Troubleshoot technical issues and guide users through solutions.",
      "Create and maintain a knowledge base of FAQs and troubleshooting guides.",
      "Gather user feedback to inform product improvements.",
      "Collaborate with product and engineering teams to escalate issues.",
      "Conduct user training sessions and webinars as needed.",
      "Monitor user satisfaction metrics and work to improve them.",
    ],
    requirements: [
      "2+ years in customer support or technical support roles.",
      "Strong understanding of personal finance concepts and tools.",
      "Excellent communication skills and a customer-first mindset.",
      "Experience with helpdesk software and ticketing systems.",
      "Ability to work independently and manage multiple inquiries.",
    ],
  },
  {
    title: "Data Analyst (Finance Focus)",
    salary: "$80,000 – $100,000",
    location: "Remote",
    about:
      "You’ll analyze user data to provide insights that drive product decisions and improve user experience. This includes tracking tool usage, identifying trends, and creating reports that inform marketing and product strategies. You’ll work closely with product managers, engineers, and designers to ensure our tools meet user needs and deliver value.",
    responsibilities: [
      "Analyze user data to identify trends and insights.",
      "Create dashboards and reports to track key performance indicators.",
      "Collaborate with product and marketing teams to inform strategies.",
      "Conduct A/B testing and analyze results to optimize user experience.",
      "Ensure data accuracy and integrity across all platforms.",
      "Document data processes and methodologies for transparency.",
      "Assist in data visualization and presentation of findings.",
    ],
    requirements: [
      "3+ years in data analysis, preferably in fintech or tech industries.",
      "Proficiency in SQL, Python, or R for data manipulation and analysis.",
      "Experience with data visualization tools (e.g., Tableau, Power BI).",
      "Strong analytical skills and attention to detail.",
      "Ability to communicate complex data insights clearly.",
    ],
  },
];
